### ISSUE TITLE
ChefVault::Exceptions::KeysNotFound in test kitchen

### ISSUE THREAD

**Issue by mhenrixon** [chef/chef-vault#92]
I am trying to test/verify that everything is production ready but the below code

``` ruby
chef_vault_item 'passwords', 'postgres_master'
```

generates the following error:

```
[2014-03-09T21:33:59+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found: http://127.0.0.1:8889/data/passwords/postgres_master_keys

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/db_server/recipes/master.rb
       ================================================================================


       ChefVault::Exceptions::KeysNotFound
       -----------------------------------
       passwords/postgres_master_keys could not be found


       Cookbook Trace:
       ---------------
  /tmp/kitchen/cache/cookbooks/chef-vault/libraries/chef_vault_item.rb:43:in `chef_vault_item'
         /tmp/kitchen/cache/cookbooks/db_server/recipes/master.rb:4:in `from_file'
```

Even though I have the data_bags folder with the in my book correct name like in the image below.

![db_master rb db_server 2014-03-09 22-24-24 2014-03-09 22-36-39](https://f.cloud.github.com/assets/106795/2369187/e2f7302c-a7d2-11e3-90af-8d6e84c1d829.png)

Could anyone shed any light on what I am doing wrong?

**Comment by mgdevstack** [comment]
@mhenrixon Same issue I am facing..
What configuration changes you done to resolve issue
```
Recipe: test::vault
         * chef_gem[chef-vault] action install (up to date)
         
         ================================================================================
         Recipe Compile Error in /tmp/kitchen/cookbooks/test/recipes/vault.rb
         ================================================================================
         
         ChefVault::Exceptions::KeysNotFound
         -----------------------------------
         secret/a_secret_keys could not be found
         
         Cookbook Trace:
         ---------------
         /tmp/kitchen/cookbooks/test/recipes/vault.rb:9:in `from_file'
         
         Relevant File Content:
         ----------------------
       /tmp/kitchen/cookbooks/test/recipes/vault.rb:
         
           2:    compile_time true if respond_to?(:compile_time)
           3:  end
       
           5:  # include_recipe 'chef-vault'
           6:  require 'chef-vault'
           7:  
           8:  # secret_stuff = chef_vault_item("secret", "a_secret")
           9>> secret_stuff = ChefVault::Item.load("secret", "a_secret")
       
          11:  Chef::Log.debug(secret_stuff) 12:  
```
![git_vault](https://cloud.githubusercontent.com/assets/8110509/11955674/f4beb82a-a8d9-11e5-8407-43ff639772e2.png)

I am using kitchen to test recipe
 knife[:vault_mode] = 'client'   # tried with and without this 
even defined data_bag path in knife.rb
tried defining attributes
```
  combined_config:
    filename: 
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: chef_solo
        data_bags_path: "./data_bags/"
      platforms:
      - name: ubuntu14
      suites:
      - name: default
        run_list:
        - recipe[test::vault]
        attributes:
          dev_mode: true
```

**Comment by moleculezz** [comment]
I am also experiencing the same thing. setting `dev_mode` to `true` did nothing for me.

```
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
```

```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  nodes_path: test/fixtures/nodes
  clients_path: test/fixtures/clients
  environments_path: test/fixtures/environments
  data_bags_path: test/fixtures/data_bags
  client_rb:
    environment: test

platforms:
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[test::windows]
    attributes:
      dev_mode: true
```

```
       Recipe: chef-vault::default
         * chef_gem[chef-vault] action install (up to date)

         ================================================================================
         Recipe Compile Error in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/test/recipes/windows.rb
         ================================================================================

         ChefVault::Exceptions::KeysNotFound
         -----------------------------------
         credentials/safe_mode_keys could not be found


         Running handlers:
       [2016-02-18T11:20:08-08:00] ERROR: Running exception handlers
         Running handlers complete
       [2016-02-18T11:20:08-08:00] ERROR: Exception handlers complete
         Chef Client failed. 0 resources updated in 12 seconds
       [2016-02-18T11:20:08-08:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2016-02-18T11:20:08-08:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-02-18T11:20:08-08:00] FATAL: ChefVault::Exceptions::KeysNotFound: credentials/safe_mode_keys could not be found
>>>>>> Converge failed on instance <default-windows-2012r2>.
>>>>>> Please see .kitchen/logs/default-windows-2012r2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [
$env:PATH = [System.Environment]::GetEnvironmentVariable("PATH","Machine")

& $env:systemdrive\opscode\chef\bin\chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb --log_level auto --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json --chef-zero-port 8889]
>>>>>> ----------------------
```
